In [ ]:
D:\English_Results

In [7]:
import pandas as pd
check2 = pd.read_parquet("D:\English_Results\embeddings_2000.parquet")

<>:2: SyntaxWarning: invalid escape sequence '\E'
<>:2: SyntaxWarning: invalid escape sequence '\E'
C:\Users\danielyoon\AppData\Local\Temp\ipykernel_40956\3951034006.py:2: SyntaxWarning: invalid escape sequence '\E'
  check2 = pd.read_parquet("D:\English_Results\embeddings_2000.parquet")

In [8]:
check2

,original_index,subset_source,row_idx,embedding
0,US-58863600-A_1,subset_1.parquet,0,"[0.01119, 0.015, 0.006977, -0.0001404, 0.00085..."
1,US-47985300-A_1,subset_1.parquet,1,"[-0.007534, 0.01633, 0.004856, -0.018, 0.00875..."
2,1113182_1,subset_1.parquet,2,"[-0.003828, 0.001009, 0.0218, 0.0004838, -0.06..."
3,US-60370700-A_1,subset_1.parquet,3,"[0.01282, 0.02943, 0.01854, 0.005737, -0.03348..."
4,US-49704000-A_1,subset_1.parquet,4,"[-0.01093, 0.00333, -0.001033, 0.01672, 0.0057..."
...,...,...,...,...
403307,US-55914400-A_3,subset_99.parquet,4024,"[0.001575, -0.005512, 0.003084, 0.0004022, -0...."
403308,6470927_1,subset_99.parquet,4025,"[-0.002653, -0.00511, 0.01894, 0.05014, -0.019..."
403309,1743339_1,subset_99.parquet,4026,"[0.03503, 0.007397, 0.011215, 0.039, -0.0417, ..."
403310,US-81904700-A_2,subset_99.parquet,4027,"[0.0005064, -0.01204, -0.00972, 0.0331, 0.0031..."
403311,US-58713600-A_2,subset_99.parquet,4028,"[-0.01826, -0.00848, -0.01813, 0.0321, -0.0238..."

In [9]:
import pandas as pd
check = pd.read_parquet("D:\English_Results\embeddings_1678.parquet")

<>:2: SyntaxWarning: invalid escape sequence '\E'
<>:2: SyntaxWarning: invalid escape sequence '\E'
C:\Users\danielyoon\AppData\Local\Temp\ipykernel_172416\3138069953.py:2: SyntaxWarning: invalid escape sequence '\E'
  check = pd.read_parquet("D:\English_Results\embeddings_1678.parquet")

In [10]:
check

,original_index,subset_source,row_idx,embedding
0,thelivelyoracles00alleuoft_7,subset_1.parquet,0,"[-0.002865, -0.05206, 0.04474, 0.01663, -0.013..."
1,diaryconsultatio72781madr_6,subset_1.parquet,1,"[0.02864, 0.003523, 0.03647, 0.00944, -0.0264,..."
2,bim_early-english-books-1641-1700_an-apology-f...,subset_1.parquet,2,"[-0.00866, -0.04437, 0.03836, 0.01255, -0.0144..."
3,diaryconsultatio5584madr_12,subset_1.parquet,3,"[0.03125, -0.008705, 0.04382, 0.02473, -0.0283..."
4,diaryconsultatio1721madr_1,subset_1.parquet,4,"[0.000791, -0.02634, 0.05984, 0.00677, -0.0537..."
...,...,...,...,...
8176,diaryconsultatio5381madr_25,subset_99.parquet,82,"[0.01851, -0.01938, 0.0385, 0.04385, -0.04785,..."
8177,bim_early-english-books-1641-1700_mr-wingates-...,subset_99.parquet,83,"[0.0244, -0.0266, 0.04364, -0.0102, -0.01636, ..."
8178,bim_early-english-books-1641-1700_the-new-poli...,subset_99.parquet,84,"[-0.0081, -0.0431, 0.0712, 0.001807, -0.01813,..."
8179,meditationsupono00grew_26,subset_99.parquet,85,"[0.04984, -0.03467, 0.0545, 0.02553, -0.05737,..."
8180,bim_early-english-books-1641-1700_a-collection...,subset_99.parquet,86,"[0.001856, -0.01962, 0.06232, 0.009026, -0.004..."

In [13]:
pd.read_parquet("D:\English_Classified\classified_1720.parquet")

<>:1: SyntaxWarning: invalid escape sequence '\E'
<>:1: SyntaxWarning: invalid escape sequence '\E'
C:\Users\danielyoon\AppData\Local\Temp\ipykernel_49232\2659855373.py:1: SyntaxWarning: invalid escape sequence '\E'
  pd.read_parquet("D:\English_Classified\classified_1720.parquet")

,identifier,predicted_quality,is_clean
0,bim_eighteenth-century_fifty-two-practical-dis...,1.874804,True
1,worksoffamousnic00mach_46,1.928561,True
2,bim_eighteenth-century_magna-britannia-et-hibe...,2.048666,True
3,bim_eighteenth-century_the-history-of-herodotu...,1.553227,True
4,bim_eighteenth-century_essays-upon-several-mor...,1.913582,True
...,...,...,...
4612,bim_eighteenth-century_the-book-of-common-pray...,1.787807,True
4613,Philosophical-Transactions-vol-30_1720_9,1.976793,True
4614,bim_eighteenth-century_a-defence-of-the-histor...,1.871974,True
4615,bim_eighteenth-century_christian-conversation-...,1.715462,True
4616,voyagesdangerous00chet_5,2.095355,True

In [13]:


pd.read_parquet(r"D:\English\1678\subset_1.parquet")

,identifier,collection,open_type,license,date,title,creator,language,language_type,word_count,token_count,text,date_raw,year
0,thelivelyoracles00alleuoft_7,US-PD-Books,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,"The lively oracles given to us; or, The Christ...",None,English,Spoken,7442,11071,'Tis the means he prefcribes for diftinguifh- ...,1678.0,1678
1,diaryconsultatio72781madr_6,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,Diary and consultation book ... [serial],Madras (India : Presidency) | Madras (India : ...,English,Spoken,6864,9325,And now Sr- I am to give you an acco' : of the...,1678.0,1678
2,bim_early-english-books-1641-1700_an-apology-f...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,"An apology for the true Christian divinity, .....","Barclay, Robert.",English,Spoken,3077,4848,lations of the Holy Spirit. z8. what differenc...,1678.0,1678
3,diaryconsultatio5584madr_12,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,Diary and consultation book ... [serial],Madras (India : Presidency) | Madras (India : ...,English,Spoken,7292,10233,into the Governour & Council the sum of Nine t...,1678.0,1678
4,diaryconsultatio1721madr_1,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,Diary and consultation book ... [serial],None,English,Spoken,7764,12162,iUcotfBs of Jf Oft £t <ffirCOl£C DIARY AND CON...,1678.0,1678
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79,bim_early-english-books-1641-1700_decameron-ph...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,"Decameron physiologicum, ... 1678","Hobbes, Thomas.",English,Spoken,3075,4558,"B. His next words are, Some things are to be c...",1678.0,1678
80,bim_early-english-books-1641-1700_the-lightnin...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,"The lightning colomne,... 1678","Colom, Jacob Aertsz",English,Spoken,7174,12116,"heed , when you will gotoanchor under th: Hecl...",1678.0,1678
81,bim_early-english-books-1641-1700_the-new-worl...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,"The new world of English words, ... 1678","Phillips, Edward.",English,Spoken,7904,13640,"Payn, the proper name of a Man, in Latin Pa- g...",1678.0,1678
82,bim_early-english-books-1641-1700_several-disc...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,Several discourses concerning the actual provi...,"Collinges, John.",English,Spoken,6850,8994,Every Precept doth imply a Promise: God hath c...,1678.0,1678
83,bim_early-english-books-1641-1700_an-alarme-to...,English-PD,Open Culture,Public Domain,1678-01-01 00:00:00+00:00,An alarme to unconverted sinners ... 1678,"Alleine, Joseph.",English,Spoken,8063,12898,"” N 4 _ 8 bn dog Ny 3 ROI TIES STE, A - _. i: ...",1678.0,1678